name: Different Types

on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'feature/**'
      #This will only if the branch we are working on is the master branch the same can be done for the pull request as well
  pull_request:
    types:
      - ready_for_review
      - closed

jobs:
  simpleHelloWorld:
    runs-on: ubuntu-18.04
    steps:
      - name: Printing hello
        run: |
          echo "This is a simple hello World pull request action"