name: using global environments

on: [push]

jobs:
  initializingRepo:
    runs-on: ubuntu-18.04
    steps:
      - name: initializing_repository
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
  cloingRepo: 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: cloning 
        run: |
          pwd
          ls -l
  logginEnvVariables:
    runs-on: ubuntu-18.04
    if: github.envet_name == 'push'
    steps:
      - name: loggin Git-hub context
        env:
          github_context: ${{toJson(github)}}
        run: |
          echo $github_context
          echo ${{github.event_name}}
      - name: running after failed step
        if: failure()
        run: echo "The preveious step failed"
      - name: running a job always 
        if: always()
        run: echo "This job will always run"