name: using global environments

on: [push]

jobs:
  initializingRepo:
    runs-on: ubuntu-18.04
    steps:
      - name: initializing_repository
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
  cloingRepo: 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: cloning 
        run: |
          pwd
          ls -l