name: practice action

on: [push]

jobs:
  simple-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: working dir
        run: |
          pwd
          ls-ltr
  processor-details:
    runs-on: ubuntu-latest
    steps:
      - name: processor name
        run: |
          import platform
          print(platform.processor())
        shell: python