name: pull request action

on: 
  push:
  pull_request:
    types: ['closed']

jobs:
  mergining-branches:
    runs-on: ubuntu-latest
    steps:
      - name: display directory
        run: |
          pwd
          ls -a
          echo "The pull request was accepted"